version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress #wp-php peut etre ?
      - mariadb
    restart: unless-stopped
    ports:
      - "443:443"
        #    volumes:
        #      - /home/pkorsako/data/web:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - /home/pkorsako/data/web:/var/www/html
    env_file:
      - .env
    networks:
      inception:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - /home/pkorsako/data/database:/var/lib/mysql
    env_file:
      - .env
    networks:
      inception:

networks:
  inception:
