FROM debian:11

RUN	apt-get update && apt-get upgrade -y && apt-get install -y \
	mariadb-server gettext

COPY	conf/50-server.cnf /etc/mysql/mariadb.conf.d/
COPY	tools/init_var.sql /etc/mysql/init_var.sql
COPY	tools/inst_mysql.sh .

RUN	mkdir /run/mysqld && chmod +x inst_mysql.sh && \
	mkdir -p /docker-entrypoint-initdb.d

CMD ["./inst_mysql.sh"] ##CMD ["mysqld"] #voir diff avec mysqld_safe 
