CREATE DATABASE IF NOT EXISTS `${WP_DB_NAME}`;
#CREATE DATABASE wordpress;

CREATE USER '${WP_DB_USER}'@'%' IDENTIFIED BY '${WP_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON `${WP_DB_NAME}`.* TO '${WP_DB_USER}'@'%';

#CREATE USER 'wpuser'@'%' IDENTIFIED BY 'password';
#GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'%';

FLUSH PRIVILEGES;
