FROM debian:11

RUN	apt-get update && apt-get -y upgrade && apt-get install -y \
	nginx openssl && \
	mkdir -p /etc/ssl /etc/ssl && \
	openssl req -newkey rsa:2048 -nodes \
	-keyout /etc/ssl/nginx.key -x509 -days 365 \
	-out /etc/ssl/nginx.crt -subj "/CN=localhost"

COPY	conf/default /etc/nginx/sites-available/.

CMD ["nginx", "-g", "daemon  off;"]
